name: arpes
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8

  - astropy
  - xarray>=0.16.1
  - h5py>=3.2.1
  - pyqtgraph==0.12

  - pint
  - pandas
  - dask
  - numpy
  - scipy
  - lmfit==1.0
  - netCDF4

  # plotting
  - colorcet
  - matplotlib>=3.0.3
  - seaborn
  - bokeh>=2.0.0
  - ipywidgets==7.0.1

  # Misc deps
  - pip

  # pip
  - pip:
      - PyQt5==5.15
      - packaging
      - deprecation
      - xlrd
      - numba
      - colorama
      - imageio
      - titlecase
      - openpyxl
      - tqdm
      - rx
      - dill
      - sphinx
      - sphinxcontrib-restbuilder
      - sphinx_rtd_theme
      - nbsphinx
      - sphinx_copybutton
      - -e .
